<?php /*pb_debug_index.phtml*/
?><!DOCTYPE html>
<html lang=en>
<head>
    <title>@package_name@ files</title>
    <style>
        <?php pb_insertFile('pb_index.cs'); ?>
    </style>
</head>
<body class=index>

    <div style="font-size:70%;">This
        page is for debugging, and should not be
        seen on a production web server on the
        Internet.  You may be able to use the <a
        href='.'>browsers local file indexing</a> too.</div>

    <div style="margin:15px;font-size:120%;">url directory: <span
        style="font-weight:bold;"><?php
        echo $_ENV['PHP_URLPATHDIR']; ?></span></div>

    <p>This is a list of all served files and directories in this version of
    this <b>@package_name@</b> service
    package installation.</p>

<?php
$this_file_out = $_ENV['PHP_OUTFILENAME'];
$this_file_in = $_ENV['PHP_INFILENAME'];
$public_dirs = @public_dirs@; // array of strings


if(file_exists('../'.$this_file_in))
    echo <<<END
    <h4><a href="../$this_file_out">back
        to parent directory</a></h4>
END;
?>


    <!-- float container div-->
    <div>


<?php

// $dir like '.' 'foo' 'foo/bar' ...
// $sufxs like [ 'html', 'phtml', 'chtml' ]
// where html is the final output suffix
function printFiles($dir, $compiled_dir, $name, $sufxs, $rlevel = 0)
{
    global $this_file_out, $public_dirs;

    $oldpwd = getcwd();
    if($dir !== '')
        chdir($dir);


    $finalsuffix = $sufxs[0];

    $suffixes = $sufxs;
    // add .in files which make $finalsuffix
    foreach($sufxs as $s)
        $suffixes[] = $s.'.in';

    $spaces = '';
    $r = $rlevel;
    while($r--)
        $spaces .= '      ';

    if($rlevel == 0)
        echo <<<END
<div class=index>
  <h4 class=index>$name</h4>

END;

    $files_list = [];

    foreach($suffixes as $t)
    {
        $files = glob('*.'.$t);
        if(count($files) < 1) continue;
        $files = preg_replace('/\.'.
            preg_quote($t).'$/', '.'.$finalsuffix, $files);
        $files_list = array_merge($files, $files_list);
    }
    $files_list = array_unique($files_list);

    if(($k = array_search(basename($this_file_out), $files_list)) !== false)
        unset($files_list[$k]);

    if(count($files_list))
    {
        foreach($files_list as $f)
        {
            $a = $f;
            if($compiled_dir !== '')
                $a = $compiled_dir.'/'.$f;
            echo <<<END
$spaces    <div class=li><a href="$a">$f</a></div>

END;
        }
    }
/*
    else
    {
        // $e = var_export($files_list, true);
        echo <<<END
$spaces    <div class=li>no $finalsuffix files</div>

END;
    }
*/
    echo <<<END
$spaces    <div class=bottom_pad></div>

END;

    $files_list = glob('*');
    foreach($files_list as $f)
    {
        if($compiled_dir !== '')
            $d = $compiled_dir . '/' . $f;
        else
            $d = $f;

        if(! is_dir($f) or $f == '.' or $f == '..') continue;
        // Skip directories that are not listed in $public_dirs
        if(array_search($d, $public_dirs) === false) continue;

        echo <<<END
$spaces    <div class=dir_box><div class=li_dir><a
$spaces      href="$d/pb_debug_index.html">$f/</a></div>

END;

        // recurse
        printFiles($f, $d, $name, $sufxs, $rlevel + 1);

        echo <<<END
$spaces    </div>

END;
    }

    if($rlevel == 0)
        echo <<<END
</div>

END;

    if($dir != '.')
        chdir($oldpwd);
}

printFiles('', '', 'html', ['html', 'chtml', 'phtml'], 0);
printFiles('', '', 'PHP', ['php', 'cphp', 'pphp'], 0);
printFiles('', '', 'javaScript', ['js', 'cjs', 'pjs'], 0);
printFiles('', '', 'CSS', ['css', 'ccss', 'pcss'], 0);
printFiles('', '', 'htm', ['htm', 'chtm', 'phtm'], 0);



?>


    </div><!-- END float container div -->

</body>
</html>
