#!/bin/bash

# Usage: pb_md_to_html in out

function usage()
{
    echo "Usage: $0 in out"
    exit 1
}

[ -n "$2" ] || usage
[ -z "$3" ] || usage

cat > "$2" <<END || exit 1
<!DOCTYPE html>
<!-- @generated_file_string@ from $1-->
<html>
<head>
  <title>${1}</title>
</head>
<body>
END

marked "$1" >> "$2" || exit 1

cat >> "$2" <<END || exit 1
</body>
</html>
END


