#!/bin/bash

# Usage: pb_php_compile in out [url_path_dir]

scriptdir="$(dirname ${BASH_SOURCE[0]})" || exit 1

include_path="${scriptdir}@include_path_relto_pb_build@"

if ! @srcdir_equals_builddir@ ; then
    # We are not building in the source tree
    if [ "@rel_include_dir@" = "" ] ; then
        include_path="$include_path:@top_src_fullpath@"
    else
        include_path="$include_path:@top_src_fullpath@/@rel_include_dir@"
    fi
fi

include_path="$include_path:$scriptdir"


header=''
tmpout="${2}.tmp"
tmpout2="${2}.tmp2"
in="$1"
out="$2"

# magic string used in pb_make.make and pb_cat_compile too
gen_file_str="@generated_file_string@ from $1"

case $2 in
    *.html|*.htm|*ht)
        header="<!-- $gen_file_str -->"
        ;;
    *.ph|*.phd|*.php)
        header="<?php /*server*/ /* $gen_file_str */\n?>"
        ;;
    *.js|*.css|*.jsp|*.cs)
        header="/* $gen_file_str */"
        ;;
    *)
        echo "unknown file type for $2"  1>&2
        exit 1
        ;;
esac


function cleanup()
{
    rm -f "$tmpout" "$tmpout2"
    if [ "$1" = 1 ] ; then
        rm -f "$out"
        echo "  $0 failed" 1>&2
        echo "  include_path=$include_path" 1>&2
    #else
    #    echo "$0 succeeded" 1>&2
    fi
    exit $1
}

set -e
set -o pipefail

# Get rid of this unnecessary env stuff that would
# be passed to the running PHP:
for var in $(env | sed -e 's!=.*$!!'| \
    grep -vE '^PATH$|^_$|^PWD$') ; do
    unset $var
done


export PHP_OUTFILENAME="$out"
export PHP_INFILENAME="$in"
export LANG="en_US.UTF-8"

if [ -n "$3" ] ; then
    export PHP_URLPATHDIR="$3"
else
    export PHP_URLPATHDIR="none"
fi


sed -e 's/<?php\s*\/\*\s*server\s*\*\//<@php@/g' $in |\
 @php_path@\
 -d "display_errors=stderr"\
 -d "error_reporting=E_ALL|E_STRICT|E_NOTICE"\
 -d "variables_order=ESCGP"\
 -d "include_path=$include_path"\
 -d "auto_prepend_file=$scriptdir/pb_auto_prepend.ph"\
 -d "auto_append_file=$scriptdir/pb_auto_append.ph"\
 -d "safe_mode_allowed_env_vars=PHP_"\
 | sed -e 's/<@php@/<?php/g' > "$tmpout" || cleanup 1


case $2 in
    *.js|*.jsp)
        echo "$header" > "$tmpout2"
        @js_compile@ "$tmpout" >> "$tmpout2" || cleanup 1
        ;;
    *.css|*.cs)
        echo "$header" > "$tmpout2"
        @css_compile@ "$tmpout" >> "$out" || cleanup 1
        ;;
    *.html|*.htm|*.ht)
        l="$(head -1 $tmpout)" || cleanup 1
        if [[ "$l" =~ '<!DOCTYPE' ]] ; then
            # first line
            echo "$l" > "$out"
            echo "$header" >> "$out"
            # the rest of it
            sed -n '2,1000000p' $tmpout >> "$out"
        else
            echo "$header" > "$out"
            cat $tmpout >> "$out"
        fi
        ;;
    *.ph|*.phd|*.php)
        echo -en "$header" > "$out"
        cat $tmpout >> "$out"
        ;;
    *)
        echo "unknown file type for $2" 1>&2
        cleanup 1
        ;;
esac

cleanup 0

